//SUMMONER SUMMARY ACTION

export const GET_SUMMONER_SUMMARY = "GET_SUMMONER_SUMMARY"
// CHAMPION USAGE
export const GET_CHAMPION_USAGE = "GET_CHAMPION_USAGE"

// GAME DATA 
export const GET_GAME_DATA = "GET_GAME_DATA"

//SEARCH

export const LAUNCH_SEARCH = "LAUNCH_SEARCH"

//TEAM

export const GET_TEAM_DATA = "GET_TEAM_DATA"
